export const ALL_COMPANY = 'ALL_COMPANY'
export const ALL_COMPANY_SUCCESS = 'ALL_COMPANY_SUCCESS'
export const ALL_COMPANY_FAILURE = 'ALL_COMPANY_FAILURE'

export const COMPANY_BY_ID = 'COMPANY_BY_ID'
export const COMPANY_BY_ID_SUCCESS = 'COMPANY_BY_ID_SUCCESS'
export const COMPANY_BY_ID_FAILURE = "COMPANY_BY_ID_FAILURE"

export const ADD_COMPANY = 'ADD_COMPANY'
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS'
export const ADD_COMPANY_FAILURE = 'ADD_COMPANY_FAILURE'

export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE'

export const REMOVE_COMPANY = 'REMOVE_COMPANY'
export const REMOVE_COMPANY_SUCCESS = 'REMOVE_COMPANY_SUCCESS'
export const REMOVE_COMPANY_FAILURE = 'REMOVE_COMPANY_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
