export const ALL_CONTACT = 'ALL_CONTACT'
export const ALL_CONTACT_SUCCESS = 'ALL_CONTACT_SUCCESS'
export const ALL_CONTACT_FAILURE = 'ALL_CONTACT_FAILURE'

export const CONTACT_BY_ID = 'CONTACT_BY_ID'
export const CONTACT_BY_ID_SUCCESS = 'CONTACT_BY_ID_SUCCESS'
export const CONTACT_BY_ID_FAILURE = "CONTACT_BY_ID_FAILURE"

export const REMOVE_CONTACT = 'REMOVE_CONTACT'
export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS'
export const REMOVE_CONTACT_FAILURE = 'REMOVE_CONTACT_FAILURE'

export const MESSAGE_BY_ID = 'MESSAGE_BY_ID'
export const MESSAGE_BY_ID_SUCCESS = 'MESSAGE_BY_ID_SUCCESS'
export const MESSAGE_BY_ID_FAILURE = 'MESSAGE_BY_ID_FAILURE'

export const ALL_MESSAGE = 'ALL_MESSAGE'
export const ALL_MESSAGE_SUCCESS = 'ALL_MESSAGE_SUCCESS'
export const ALL_MESSAGE_FAILURES = 'ALL_MESSAGE_FAILURES'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
