export const ALL_PAYMENT = 'ALL_PAYMENT'
export const ALL_PAYMENT_SUCCESS = 'ALL_PAYMENT_SUCCESS'
export const ALL_PAYMENT_FAILURE = 'ALL_PAYMENT_FAILURE'

export const PAYMENT_BY_ID = 'PAYMENT_BY_ID'
export const PAYMENT_BY_ID_SUCCESS = 'PAYMENT_BY_ID_SUCCESS'
export const PAYMENT_BY_ID_FAILURE = "PAYMENT_BY_ID_FAILURE"

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
